# Generated by Django 3.0.9 on 2020-12-23 16:48

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import index.noticias.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('tipo', models.CharField(choices=[('IMAGEN', 'IMAGEN'), ('VIDEO', 'VIDEO'), ('ENLACE', 'ENLACE'), ('AUDIO', 'AUDIO')], default='IMAGEN', max_length=30)),
                ('formato', models.FileField(blank=True, null=True, upload_to=index.noticias.models.generate_path)),
                ('enlace', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Máximo 20 Caracteres', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Etiquetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Máximo 20 Caracteres', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('titulo', models.CharField(blank=True, help_text='Texto de no mas de 120 caracteres..!!', max_length=120, null=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='noticias/portada')),
                ('destacada', models.BooleanField(default=False)),
                ('visitas', models.IntegerField(default=1)),
                ('metadatos', models.TextField(blank=True, null=True)),
                ('detalle', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Categorias')),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticias.Etiquetas')),
            ],
        ),
    ]
