# Generated by Django 3.0.9 on 2020-12-23 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dignidad', models.CharField(choices=[('ASAMBLEISTA', 'ASAMBLEISTA'), ('PRESIDENTE', 'PRESIDENTE'), ('ALCALDE', 'ALCALDE'), ('PREFECTO', 'PREFECTO'), ('CONCEJALES', 'CONCEJALES')], max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='encuesta')),
                ('consejalRural', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartidosPoliticos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('lista', models.IntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Recintos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Juntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], max_length=60)),
                ('numero', models.CharField(max_length=20)),
                ('recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.Recintos')),
            ],
        ),
        migrations.CreateModel(
            name='ConteoVotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_votos', models.IntegerField(default=0)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participantes.Candidatos')),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.Juntas')),
            ],
        ),
        migrations.AddField(
            model_name='candidatos',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participantes.PartidosPoliticos'),
        ),
    ]
